<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	| 附加编译的类
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| 这里你可以指定附加类，包含到
	| generated by the `artisan optimize` command. These should be classes
	| 由 `artisan optimize` 命令生成的编译文件中。这些必须是类文件，
	| that are included on basically every request into the application.
	| 并且是基本上每一个到应用程序的请求都应包含的。
	|
	*/



);
